[project]
name = "sever"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.115.12",
    "openai>=1.82.0",
    "uvicorn[standard]>=0.34.2",
]
